version: "3"

services:
  server:
    image: sohanyu/rss-reader:1.0.0
    container_name: rss-reader
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/config.json:/app/config.json"
