name: Git Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  tag:
    name: add tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get current version
        id: current_version
        run: |
          version=$(grep -oP '(?<=<Version>).*?(?=<\/Version>)' ./current_version.md)
          echo "Curent version: $version"
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Tag and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag="${{ steps.current_version.outputs.current_version }}"
          git push origin --delete "$new_tag" || true
          git tag -f "$new_tag"
          git push origin "$new_tag"
